// Generated by Selenium IDE
using AventStack.ExtentReports;
using AventStack.ExtentReports.Reporter;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Support.UI;
namespace AEADO
{
    [TestFixture]
    public class TC10HomeSubscribe
    {
        private IWebDriver driver;
        private WebDriverWait wait;
        private HelperMethods helper;
        private ExtentReports reports;
        [SetUp]
        public void SetUp()
        {
            ChromeOptions options = new ChromeOptions();
            options.AddArgument("headless");
            driver = new ChromeDriver(options);
            wait = new WebDriverWait(driver, TimeSpan.FromSeconds(15));
            helper = new HelperMethods();
            reports = new ExtentReports();
            ExtentSparkReporter reporter = new ExtentSparkReporter("..\\..\\..\\AEADO\\TC10.html");
            reports.AttachReporter(reporter);
        }

        [TearDown]
        protected void TearDown()
        {
            driver.Quit();
            reports.Flush();
        }
        [Test]
        public void tC10HomeSubscribe()
        {
            helper.NavigateToHome(driver, reports);
            try
            {
                IWebElement sub = driver.FindElement(By.XPath("//*[@id=\"footer\"]/div[1]/div/div/div[2]/div/h2"));
                if (sub.Text.Equals("SUBSCRIPTION") && sub.Displayed)
                {
                    reports.CreateTest("Subcription Text Displayed").Pass("Subscription text at the bottom of the webpage is displayed.");
                } else
                {
                    reports.CreateTest("Subcription Text Displayed").Fail("Text at the bottom of the webpage is either not displayed or does not equal \"Subscription\".");

                }
            } catch (NoSuchElementException ex)
            {
                reports.CreateTest("Subcription Text Displayed").Fail("Subscription text at the bottom of the webpage could not be found. See: " + ex.Message);
            }
            driver.FindElement(By.XPath("//*[@id=\"susbscribe_email\"]")).Clear();
            driver.FindElement(By.XPath("//*[@id=\"susbscribe_email\"]")).SendKeys("jsmith@email.org");
            driver.FindElement(By.XPath("//*[@id=\"subscribe\"]")).Click();
            try
            {
                IWebElement sub = driver.FindElement(By.XPath("//*[@id=\"success-subscribe\"]/div"));
                if (sub.Text.Equals("You have been successfully subscribed!") && sub.Displayed)
                {
                    reports.CreateTest("Subcription confirmation displayed").Pass("Subscription confirmation message is displayed.");
                } else
                {
                    reports.CreateTest("Subcription confirmation displayed").Fail("Subscription confirmation message does not match expected text or is not displayed.");
                }
            }
            catch (NoSuchElementException ex)
            {
                reports.CreateTest("Subcription confirmation displayed").Fail("Subscription confirmation message could not be found. See: " + ex.Message);
            }

            Assert.That(reports.Status.Equals(Status.Pass));
        }
    }
}
